### PR TITLE
Fix #93: Add non-verbose mode for ErrorHandler

### LINKED ISSUE #93: Ability for error handler to be switched to non-verbose mode
Useful for production where you don't want stack traces and details exposed.

### PR DESCRIPTION
**Pull request by samdark**
That would allow configuring it like the following:

```php
Yiisoft\Yii\Web\ErrorHandler\ErrorHandler::class => function (ContainerInterface $container) {
    $errorHandler = $container->get(ErrorHandler::class);
    return $errorHandler->withoutExposedDetails();
},
```

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #93

### CODE REVIEW

File: src/ErrorHandler/JsonRenderer.php [hunk 1]
```diff
@@ -7,6 +7,13 @@
 final class JsonRenderer extends ThrowableRenderer
 {
     public function render(\Throwable $t): string
+    {
+        return json_encode([
```
Comment (rustamwin) [inline src/ErrorHandler/JsonRenderer.php]: could we use `yiisoft/json`?

**Comment by schmunk42** [comment]
Would be nice to have a use-case in the docs.

**Comment by samdark** [comment]
@schmunk42 docs on error handler are to be done. Going to work on it soon.

File: src/ErrorHandler/JsonRenderer.php (hunk 1 above)
Comment (samdark) [reply src/ErrorHandler/JsonRenderer.php]: Yes but I see no benefit of doing it in this particular case.

**Review by rustamwin — APPROVED** [review]
